### ISSUE TITLE
Error starting from h5ad [BUG]

### ISSUE THREAD

**Issue by cbravo93** [vib-singlecell-nf/vsn-pipelines#300]
**Describe the bug**
When providing a h5ad file as input, the pipeline crashes when reading the file. See error below. Example files are available to test this.

**To Reproduce**
1. Configure with these options:

```
nextflow config vib-singlecell-nf/vsn-pipelines \
    -profile h5ad,singularity,single_sample,scrublet > single_sample_scrublet.config
```

2. Run using this entry point:

```
nextflow -C single_sample_scrublet.config run vib-singlecell-nf/vsn-pipelines -entry single_sample_scrublet
```

3. See error:

```
[Kleshchevnikov_snRNA_brain_slice_8, /staging/leuven/stg_00002/lcb/cbravo/brain_mpra/enhancer_selection/scRNA/Kleshchevnikov/data/Kleshchevnikov_snRNA_brain_slice_8.h5ad, h5ad, h5ad]
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'single_sample_scrublet:SC__FILE_CONVERTER (1)'

Caused by:
  Process `single_sample_scrublet:SC__FILE_CONVERTER (1)` terminated with an error exit status (1)

Command executed:

  /user/leuven/313/vsc31305/.nextflow/assets/vib-singlecell-nf/vsn-pipelines/src/utils/bin/sc_file_converter.py             --sample-id "Kleshchevnikov_snRNA_brain_slice_8"             --make-var-index-unique false             --tag-cell-with-sample-id true             --input-format h5ad             --output-format h5ad             Kleshchevnikov_snRNA_brain_slice_8.h5ad             "Kleshchevnikov_snRNA_brain_slice_8.SC__FILE_CONVERTER.h5ad"

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/user/leuven/313/vsc31305/.nextflow/assets/vib-singlecell-nf/vsn-pipelines/src/utils/bin/sc_file_converter.py", line 231, in <module>
      FILE_PATH_IN
    File "/opt/venv/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
      constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
    File "/opt/venv/lib/python3.7/site-packages/anndata/readwrite/read.py", line 502, in _read_args_from_h5ad
      return AnnData._args_from_dict(d)
    File "/opt/venv/lib/python3.7/site-packages/anndata/core/anndata.py", line 2157, in _args_from_dict
      if key in d_true_keys[true_key].dtype.names:
  AttributeError: 'dict' object has no attribute 'dtype'

Work dir:
  /ddn1/vol1/staging/leuven/stg_00002/lcb/cbravo/brain_mpra/enhancer_selection/scRNA/Kleshchevnikov/work/95/d214b8ecbd3a2dac1002781b2c747a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Please complete the following information:**
 - OS: [e.g. Ubuntu]
 - Nextflow Version: [e.g. 20.04.1]
 - vsn-pipelines Version: [e.g. 0.14.2]

**Comment by cbravo93** [comment]
It is very likely related to this issue in anndata: https://github.com/theislab/anndata/issues/287

**Comment by dweemx** [comment]
Yeah indeed. VSN-Pipelines currently uses `scanpy==1.4.4.post1`. And the `h5ad` file you're using has been built with higher version (probably `scanpy==1.6`.  I would not consider a bug tough, Scanpy is backward compatible but not forward compatible.
We should definitely update VSN to work with `anndata>=1.7` ( `scanpy>=1.6`) @cflerin @KrisDavie

**Comment by KrisDavie** [comment]
Closed #358
